#nullable enable
namespace CustomPC;

partial class BuilderForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(1036, 40);
        heading.TabIndex = 0;
        heading.Text = "PC builder";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(1036, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Select seven components. Availability is checked again when you confirm the order.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        part0Label = new Label();
        part0Label.Name = "part0Label";
        part0Label.Location = new Point(32, 126);
        part0Label.Size = new Size(570, 28);
        part0Label.TabIndex = 2;
        part0Label.Text = "CPU";
        part0Label.UseMnemonic = false;
        Controls.Add(part0Label);
        part0 = new ComboBox();
        part0.Name = "part0";
        part0.Location = new Point(32, 156);
        part0.Size = new Size(570, 32);
        part0.TabIndex = 3;
        part0.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part0);
        part1Label = new Label();
        part1Label.Name = "part1Label";
        part1Label.Location = new Point(32, 196);
        part1Label.Size = new Size(570, 28);
        part1Label.TabIndex = 4;
        part1Label.Text = "Motherboard";
        part1Label.UseMnemonic = false;
        Controls.Add(part1Label);
        part1 = new ComboBox();
        part1.Name = "part1";
        part1.Location = new Point(32, 226);
        part1.Size = new Size(570, 32);
        part1.TabIndex = 5;
        part1.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part1);
        part2Label = new Label();
        part2Label.Name = "part2Label";
        part2Label.Location = new Point(32, 266);
        part2Label.Size = new Size(570, 28);
        part2Label.TabIndex = 6;
        part2Label.Text = "RAM";
        part2Label.UseMnemonic = false;
        Controls.Add(part2Label);
        part2 = new ComboBox();
        part2.Name = "part2";
        part2.Location = new Point(32, 296);
        part2.Size = new Size(570, 32);
        part2.TabIndex = 7;
        part2.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part2);
        part3Label = new Label();
        part3Label.Name = "part3Label";
        part3Label.Location = new Point(32, 336);
        part3Label.Size = new Size(570, 28);
        part3Label.TabIndex = 8;
        part3Label.Text = "GPU";
        part3Label.UseMnemonic = false;
        Controls.Add(part3Label);
        part3 = new ComboBox();
        part3.Name = "part3";
        part3.Location = new Point(32, 366);
        part3.Size = new Size(570, 32);
        part3.TabIndex = 9;
        part3.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part3);
        part4Label = new Label();
        part4Label.Name = "part4Label";
        part4Label.Location = new Point(32, 406);
        part4Label.Size = new Size(570, 28);
        part4Label.TabIndex = 10;
        part4Label.Text = "Storage";
        part4Label.UseMnemonic = false;
        Controls.Add(part4Label);
        part4 = new ComboBox();
        part4.Name = "part4";
        part4.Location = new Point(32, 436);
        part4.Size = new Size(570, 32);
        part4.TabIndex = 11;
        part4.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part4);
        part5Label = new Label();
        part5Label.Name = "part5Label";
        part5Label.Location = new Point(32, 476);
        part5Label.Size = new Size(570, 28);
        part5Label.TabIndex = 12;
        part5Label.Text = "Power Supply";
        part5Label.UseMnemonic = false;
        Controls.Add(part5Label);
        part5 = new ComboBox();
        part5.Name = "part5";
        part5.Location = new Point(32, 506);
        part5.Size = new Size(570, 32);
        part5.TabIndex = 13;
        part5.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part5);
        part6Label = new Label();
        part6Label.Name = "part6Label";
        part6Label.Location = new Point(32, 546);
        part6Label.Size = new Size(570, 28);
        part6Label.TabIndex = 14;
        part6Label.Text = "Case";
        part6Label.UseMnemonic = false;
        Controls.Add(part6Label);
        part6 = new ComboBox();
        part6.Name = "part6";
        part6.Location = new Point(32, 576);
        part6.Size = new Size(570, 32);
        part6.TabIndex = 15;
        part6.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(part6);
        customerLabel = new Label();
        customerLabel.Name = "customerLabel";
        customerLabel.Location = new Point(640, 126);
        customerLabel.Size = new Size(410, 28);
        customerLabel.TabIndex = 16;
        customerLabel.Text = "Customer account";
        customerLabel.UseMnemonic = false;
        Controls.Add(customerLabel);
        customer = new ComboBox();
        customer.Name = "customer";
        customer.Location = new Point(640, 158);
        customer.Size = new Size(410, 32);
        customer.TabIndex = 17;
        customer.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(customer);
        total = new Label();
        total.Name = "total";
        total.Location = new Point(640, 218);
        total.Size = new Size(420, 50);
        total.TabIndex = 18;
        total.Text = "Build total: PHP 0.00";
        total.UseMnemonic = false;
        total.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
        Controls.Add(total);
        validation = new Label();
        validation.Name = "validation";
        validation.Location = new Point(640, 288);
        validation.Size = new Size(410, 190);
        validation.TabIndex = 19;
        validation.Text = "Select one component in each category.";
        validation.UseMnemonic = false;
        Controls.Add(validation);
        limits = new Label();
        limits.Name = "limits";
        limits.Location = new Point(640, 480);
        limits.Size = new Size(410, 90);
        limits.TabIndex = 20;
        limits.Text = "Checks cover stored socket, RAM type and PSU wattage.\nCase dimensions and cooler clearance require staff review.";
        limits.UseMnemonic = false;
        Controls.Add(limits);
        submit = new Button();
        submit.Name = "submit";
        submit.Location = new Point(640, 610);
        submit.Size = new Size(280, 40);
        submit.TabIndex = 21;
        submit.Text = "Confirm build & order";
        submit.BackColor = Color.FromArgb(15, 98, 84);
        submit.ForeColor = Color.White;
        submit.FlatStyle = FlatStyle.Flat;
        submit.FlatAppearance.BorderSize = 0;
        submit.Cursor = Cursors.Hand;
        submit.UseMnemonic = false;
        Controls.Add(submit);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1100, 720);
        MinimumSize = new Size(1116, 759);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | PC builder";
        Name = "BuilderForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label part0Label = null!;
    private ComboBox part0 = null!;
    private Label part1Label = null!;
    private ComboBox part1 = null!;
    private Label part2Label = null!;
    private ComboBox part2 = null!;
    private Label part3Label = null!;
    private ComboBox part3 = null!;
    private Label part4Label = null!;
    private ComboBox part4 = null!;
    private Label part5Label = null!;
    private ComboBox part5 = null!;
    private Label part6Label = null!;
    private ComboBox part6 = null!;
    private Label customerLabel = null!;
    private ComboBox customer = null!;
    private Label total = null!;
    private Label validation = null!;
    private Label limits = null!;
    private Button submit = null!;
}
