#nullable enable
namespace CustomPC;

partial class CatalogForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(1036, 40);
        heading.TabIndex = 0;
        heading.Text = "Parts catalog";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(1036, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Search components by name, brand or specifications. Prices are in Philippine pesos.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        searchLabel = new Label();
        searchLabel.Name = "searchLabel";
        searchLabel.Location = new Point(32, 120);
        searchLabel.Size = new Size(380, 28);
        searchLabel.TabIndex = 2;
        searchLabel.Text = "Search";
        searchLabel.UseMnemonic = false;
        Controls.Add(searchLabel);
        search = new TextBox();
        search.Name = "search";
        search.Location = new Point(32, 150);
        search.Size = new Size(380, 32);
        search.TabIndex = 3;
        Controls.Add(search);
        categoryLabel = new Label();
        categoryLabel.Name = "categoryLabel";
        categoryLabel.Location = new Point(436, 120);
        categoryLabel.Size = new Size(220, 28);
        categoryLabel.TabIndex = 4;
        categoryLabel.Text = "Category";
        categoryLabel.UseMnemonic = false;
        Controls.Add(categoryLabel);
        category = new ComboBox();
        category.Name = "category";
        category.Location = new Point(436, 150);
        category.Size = new Size(220, 32);
        category.TabIndex = 5;
        category.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(category);
        availabilityLabel = new Label();
        availabilityLabel.Name = "availabilityLabel";
        availabilityLabel.Location = new Point(680, 120);
        availabilityLabel.Size = new Size(220, 28);
        availabilityLabel.TabIndex = 6;
        availabilityLabel.Text = "Availability";
        availabilityLabel.UseMnemonic = false;
        Controls.Add(availabilityLabel);
        availability = new ComboBox();
        availability.Name = "availability";
        availability.Location = new Point(680, 150);
        availability.Size = new Size(220, 32);
        availability.TabIndex = 7;
        availability.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(availability);
        grid = new DataGridView();
        grid.Name = "grid";
        grid.Location = new Point(32, 190);
        grid.Size = new Size(1036, 430);
        grid.TabIndex = 8;
        grid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        grid.BackgroundColor = Color.White;
        grid.BorderStyle = BorderStyle.None;
        grid.ReadOnly = true;
        grid.AllowUserToAddRows = false;
        grid.AllowUserToDeleteRows = false;
        grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        grid.MultiSelect = false;
        grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        grid.RowHeadersVisible = false;
        grid.EnableHeadersVisualStyles = false;
        grid.ColumnHeadersHeight = 42;
        grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
        grid.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
        grid.RowTemplate.Height = 38;
        grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(204, 235, 225);
        grid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        Controls.Add(grid);
        refresh = new Button();
        refresh.Name = "refresh";
        refresh.Location = new Point(32, 644);
        refresh.Size = new Size(220, 40);
        refresh.TabIndex = 9;
        refresh.Text = "Refresh availability";
        refresh.BackColor = Color.FromArgb(15, 98, 84);
        refresh.ForeColor = Color.White;
        refresh.FlatStyle = FlatStyle.Flat;
        refresh.FlatAppearance.BorderSize = 0;
        refresh.Cursor = Cursors.Hand;
        refresh.UseMnemonic = false;
        Controls.Add(refresh);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1100, 720);
        MinimumSize = new Size(1116, 759);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Parts catalog";
        Name = "CatalogForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label searchLabel = null!;
    private TextBox search = null!;
    private Label categoryLabel = null!;
    private ComboBox category = null!;
    private Label availabilityLabel = null!;
    private ComboBox availability = null!;
    private DataGridView grid = null!;
    private Button refresh = null!;
}
