#nullable enable
namespace CustomPC;

partial class DashboardForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(1036, 40);
        heading.TabIndex = 0;
        heading.Text = "CustomPC";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(1036, 40);
        subheading.TabIndex = 1;
        subheading.Text = "CUSTOM PC BUILDER & ORDER MANAGEMENT";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        identity = new Label();
        identity.Name = "identity";
        identity.Location = new Point(280, 130);
        identity.Size = new Size(740, 32);
        identity.TabIndex = 2;
        identity.Text = "Guest workspace";
        identity.UseMnemonic = false;
        Controls.Add(identity);
        metrics = new Label();
        metrics.Name = "metrics";
        metrics.Location = new Point(280, 184);
        metrics.Size = new Size(740, 90);
        metrics.TabIndex = 3;
        metrics.Text = "Your next PC starts here";
        metrics.UseMnemonic = false;
        metrics.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
        Controls.Add(metrics);
        guide = new Label();
        guide.Name = "guide";
        guide.Location = new Point(280, 300);
        guide.Size = new Size(730, 260);
        guide.TabIndex = 4;
        guide.Text = "01   Browse available components\n\n02   Select a compatible build\n\n03   Confirm your order and keep the receipt\n\n04   Pay at the store within 24 hours\n\n05   Track assembly and collect your PC";
        guide.UseMnemonic = false;
        Controls.Add(guide);
        footer = new Label();
        footer.Name = "footer";
        footer.Location = new Point(280, 620);
        footer.Size = new Size(740, 50);
        footer.TabIndex = 5;
        footer.Text = "Store payment and pickup only. Compatibility uses stored specifications.";
        footer.UseMnemonic = false;
        Controls.Add(footer);
        signout = new Button();
        signout.Name = "signout";
        signout.Location = new Point(32, 630);
        signout.Size = new Size(216, 40);
        signout.TabIndex = 6;
        signout.Text = "Sign out / Switch account";
        signout.BackColor = Color.FromArgb(15, 98, 84);
        signout.ForeColor = Color.White;
        signout.FlatStyle = FlatStyle.Flat;
        signout.FlatAppearance.BorderSize = 0;
        signout.Cursor = Cursors.Hand;
        signout.UseMnemonic = false;
        Controls.Add(signout);
        catalog = new Button();
        catalog.Name = "catalog";
        catalog.Location = new Point(32, 132);
        catalog.Size = new Size(216, 40);
        catalog.TabIndex = 7;
        catalog.Text = "Parts catalog";
        catalog.BackColor = Color.FromArgb(15, 98, 84);
        catalog.ForeColor = Color.White;
        catalog.FlatStyle = FlatStyle.Flat;
        catalog.FlatAppearance.BorderSize = 0;
        catalog.Cursor = Cursors.Hand;
        catalog.UseMnemonic = false;
        Controls.Add(catalog);
        builder = new Button();
        builder.Name = "builder";
        builder.Location = new Point(32, 190);
        builder.Size = new Size(216, 40);
        builder.TabIndex = 8;
        builder.Text = "PC builder";
        builder.BackColor = Color.FromArgb(15, 98, 84);
        builder.ForeColor = Color.White;
        builder.FlatStyle = FlatStyle.Flat;
        builder.FlatAppearance.BorderSize = 0;
        builder.Cursor = Cursors.Hand;
        builder.UseMnemonic = false;
        Controls.Add(builder);
        orders = new Button();
        orders.Name = "orders";
        orders.Location = new Point(32, 248);
        orders.Size = new Size(216, 40);
        orders.TabIndex = 9;
        orders.Text = "Orders & payments";
        orders.BackColor = Color.FromArgb(15, 98, 84);
        orders.ForeColor = Color.White;
        orders.FlatStyle = FlatStyle.Flat;
        orders.FlatAppearance.BorderSize = 0;
        orders.Cursor = Cursors.Hand;
        orders.UseMnemonic = false;
        Controls.Add(orders);
        inventory = new Button();
        inventory.Name = "inventory";
        inventory.Location = new Point(32, 306);
        inventory.Size = new Size(216, 40);
        inventory.TabIndex = 10;
        inventory.Text = "Parts & inventory";
        inventory.BackColor = Color.FromArgb(15, 98, 84);
        inventory.ForeColor = Color.White;
        inventory.FlatStyle = FlatStyle.Flat;
        inventory.FlatAppearance.BorderSize = 0;
        inventory.Cursor = Cursors.Hand;
        inventory.UseMnemonic = false;
        Controls.Add(inventory);
        suppliers = new Button();
        suppliers.Name = "suppliers";
        suppliers.Location = new Point(32, 364);
        suppliers.Size = new Size(216, 40);
        suppliers.TabIndex = 11;
        suppliers.Text = "Suppliers";
        suppliers.BackColor = Color.FromArgb(15, 98, 84);
        suppliers.ForeColor = Color.White;
        suppliers.FlatStyle = FlatStyle.Flat;
        suppliers.FlatAppearance.BorderSize = 0;
        suppliers.Cursor = Cursors.Hand;
        suppliers.UseMnemonic = false;
        Controls.Add(suppliers);
        users = new Button();
        users.Name = "users";
        users.Location = new Point(32, 422);
        users.Size = new Size(216, 40);
        users.TabIndex = 12;
        users.Text = "User accounts";
        users.BackColor = Color.FromArgb(15, 98, 84);
        users.ForeColor = Color.White;
        users.FlatStyle = FlatStyle.Flat;
        users.FlatAppearance.BorderSize = 0;
        users.Cursor = Cursors.Hand;
        users.UseMnemonic = false;
        Controls.Add(users);
        rules = new Button();
        rules.Name = "rules";
        rules.Location = new Point(32, 480);
        rules.Size = new Size(216, 40);
        rules.TabIndex = 13;
        rules.Text = "Compatibility rules";
        rules.BackColor = Color.FromArgb(15, 98, 84);
        rules.ForeColor = Color.White;
        rules.FlatStyle = FlatStyle.Flat;
        rules.FlatAppearance.BorderSize = 0;
        rules.Cursor = Cursors.Hand;
        rules.UseMnemonic = false;
        Controls.Add(rules);
        reports = new Button();
        reports.Name = "reports";
        reports.Location = new Point(32, 538);
        reports.Size = new Size(216, 40);
        reports.TabIndex = 14;
        reports.Text = "Reports";
        reports.BackColor = Color.FromArgb(15, 98, 84);
        reports.ForeColor = Color.White;
        reports.FlatStyle = FlatStyle.Flat;
        reports.FlatAppearance.BorderSize = 0;
        reports.Cursor = Cursors.Hand;
        reports.UseMnemonic = false;
        Controls.Add(reports);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1100, 720);
        MinimumSize = new Size(1116, 759);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | CustomPC";
        Name = "DashboardForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label identity = null!;
    private Label metrics = null!;
    private Label guide = null!;
    private Label footer = null!;
    private Button signout = null!;
    private Button catalog = null!;
    private Button builder = null!;
    private Button orders = null!;
    private Button inventory = null!;
    private Button suppliers = null!;
    private Button users = null!;
    private Button rules = null!;
    private Button reports = null!;
}
