#nullable enable
namespace CustomPC;

partial class InventoryForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(1036, 40);
        heading.TabIndex = 0;
        heading.Text = "Parts & inventory";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(1036, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Available stock excludes active reservations. Archive parts to remove them from the catalog.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        searchLabel = new Label();
        searchLabel.Name = "searchLabel";
        searchLabel.Location = new Point(32, 120);
        searchLabel.Size = new Size(420, 28);
        searchLabel.TabIndex = 2;
        searchLabel.Text = "Search parts";
        searchLabel.UseMnemonic = false;
        Controls.Add(searchLabel);
        search = new TextBox();
        search.Name = "search";
        search.Location = new Point(32, 150);
        search.Size = new Size(420, 32);
        search.TabIndex = 3;
        Controls.Add(search);
        stockLabel = new Label();
        stockLabel.Name = "stockLabel";
        stockLabel.Location = new Point(476, 120);
        stockLabel.Size = new Size(250, 28);
        stockLabel.TabIndex = 4;
        stockLabel.Text = "Stock status";
        stockLabel.UseMnemonic = false;
        Controls.Add(stockLabel);
        stockFilter = new ComboBox();
        stockFilter.Name = "stockFilter";
        stockFilter.Location = new Point(476, 150);
        stockFilter.Size = new Size(250, 32);
        stockFilter.TabIndex = 5;
        stockFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(stockFilter);
        archived = new CheckBox();
        archived.Name = "archived";
        archived.Location = new Point(750, 150);
        archived.Size = new Size(280, 32);
        archived.TabIndex = 6;
        archived.Text = "Include archived";
        Controls.Add(archived);
        grid = new DataGridView();
        grid.Name = "grid";
        grid.Location = new Point(32, 202);
        grid.Size = new Size(1036, 408);
        grid.TabIndex = 7;
        grid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        grid.BackgroundColor = Color.White;
        grid.BorderStyle = BorderStyle.None;
        grid.ReadOnly = true;
        grid.AllowUserToAddRows = false;
        grid.AllowUserToDeleteRows = false;
        grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        grid.MultiSelect = false;
        grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        grid.RowHeadersVisible = false;
        grid.EnableHeadersVisualStyles = false;
        grid.ColumnHeadersHeight = 42;
        grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
        grid.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
        grid.RowTemplate.Height = 38;
        grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(204, 235, 225);
        grid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        Controls.Add(grid);
        add = new Button();
        add.Name = "add";
        add.Location = new Point(32, 636);
        add.Size = new Size(170, 40);
        add.TabIndex = 8;
        add.Text = "Add part";
        add.BackColor = Color.FromArgb(15, 98, 84);
        add.ForeColor = Color.White;
        add.FlatStyle = FlatStyle.Flat;
        add.FlatAppearance.BorderSize = 0;
        add.Cursor = Cursors.Hand;
        add.UseMnemonic = false;
        Controls.Add(add);
        edit = new Button();
        edit.Name = "edit";
        edit.Location = new Point(218, 636);
        edit.Size = new Size(210, 40);
        edit.TabIndex = 9;
        edit.Text = "Edit selected part";
        edit.BackColor = Color.FromArgb(15, 98, 84);
        edit.ForeColor = Color.White;
        edit.FlatStyle = FlatStyle.Flat;
        edit.FlatAppearance.BorderSize = 0;
        edit.Cursor = Cursors.Hand;
        edit.UseMnemonic = false;
        Controls.Add(edit);
        adjust = new Button();
        adjust.Name = "adjust";
        adjust.Location = new Point(444, 636);
        adjust.Size = new Size(180, 40);
        adjust.TabIndex = 10;
        adjust.Text = "Adjust stock";
        adjust.BackColor = Color.FromArgb(15, 98, 84);
        adjust.ForeColor = Color.White;
        adjust.FlatStyle = FlatStyle.Flat;
        adjust.FlatAppearance.BorderSize = 0;
        adjust.Cursor = Cursors.Hand;
        adjust.UseMnemonic = false;
        Controls.Add(adjust);
        history = new Button();
        history.Name = "history";
        history.Location = new Point(640, 636);
        history.Size = new Size(208, 40);
        history.TabIndex = 11;
        history.Text = "Movement history";
        history.BackColor = Color.FromArgb(15, 98, 84);
        history.ForeColor = Color.White;
        history.FlatStyle = FlatStyle.Flat;
        history.FlatAppearance.BorderSize = 0;
        history.Cursor = Cursors.Hand;
        history.UseMnemonic = false;
        Controls.Add(history);
        refresh = new Button();
        refresh.Name = "refresh";
        refresh.Location = new Point(864, 636);
        refresh.Size = new Size(204, 40);
        refresh.TabIndex = 12;
        refresh.Text = "Refresh";
        refresh.BackColor = Color.FromArgb(15, 98, 84);
        refresh.ForeColor = Color.White;
        refresh.FlatStyle = FlatStyle.Flat;
        refresh.FlatAppearance.BorderSize = 0;
        refresh.Cursor = Cursors.Hand;
        refresh.UseMnemonic = false;
        Controls.Add(refresh);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1100, 720);
        MinimumSize = new Size(1116, 759);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Parts & inventory";
        Name = "InventoryForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label searchLabel = null!;
    private TextBox search = null!;
    private Label stockLabel = null!;
    private ComboBox stockFilter = null!;
    private CheckBox archived = null!;
    private DataGridView grid = null!;
    private Button add = null!;
    private Button edit = null!;
    private Button adjust = null!;
    private Button history = null!;
    private Button refresh = null!;
}
