#nullable enable
namespace CustomPC;

partial class LoginForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(516, 40);
        heading.TabIndex = 0;
        heading.Text = "Welcome to CustomPC";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(516, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Build your PC. Reserve your parts. Pay and pick up at the store.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        emailLabel = new Label();
        emailLabel.Name = "emailLabel";
        emailLabel.Location = new Point(32, 144);
        emailLabel.Size = new Size(480, 28);
        emailLabel.TabIndex = 2;
        emailLabel.Text = "Email address";
        emailLabel.UseMnemonic = false;
        Controls.Add(emailLabel);
        email = new TextBox();
        email.Name = "email";
        email.Location = new Point(32, 174);
        email.Size = new Size(480, 32);
        email.TabIndex = 3;
        Controls.Add(email);
        passwordLabel = new Label();
        passwordLabel.Name = "passwordLabel";
        passwordLabel.Location = new Point(32, 230);
        passwordLabel.Size = new Size(480, 28);
        passwordLabel.TabIndex = 4;
        passwordLabel.Text = "Password";
        passwordLabel.UseMnemonic = false;
        Controls.Add(passwordLabel);
        password = new TextBox();
        password.Name = "password";
        password.Location = new Point(32, 260);
        password.Size = new Size(480, 32);
        password.TabIndex = 5;
        password.UseSystemPasswordChar = true;
        Controls.Add(password);
        login = new Button();
        login.Name = "login";
        login.Location = new Point(32, 328);
        login.Size = new Size(480, 40);
        login.TabIndex = 6;
        login.Text = "Sign in";
        login.BackColor = Color.FromArgb(15, 98, 84);
        login.ForeColor = Color.White;
        login.FlatStyle = FlatStyle.Flat;
        login.FlatAppearance.BorderSize = 0;
        login.Cursor = Cursors.Hand;
        login.UseMnemonic = false;
        Controls.Add(login);
        register = new Button();
        register.Name = "register";
        register.Location = new Point(32, 384);
        register.Size = new Size(232, 40);
        register.TabIndex = 7;
        register.Text = "Create customer account";
        register.BackColor = Color.FromArgb(15, 98, 84);
        register.ForeColor = Color.White;
        register.FlatStyle = FlatStyle.Flat;
        register.FlatAppearance.BorderSize = 0;
        register.Cursor = Cursors.Hand;
        register.UseMnemonic = false;
        Controls.Add(register);
        guest = new Button();
        guest.Name = "guest";
        guest.Location = new Point(280, 384);
        guest.Size = new Size(232, 40);
        guest.TabIndex = 8;
        guest.Text = "Browse as guest";
        guest.BackColor = Color.FromArgb(15, 98, 84);
        guest.ForeColor = Color.White;
        guest.FlatStyle = FlatStyle.Flat;
        guest.FlatAppearance.BorderSize = 0;
        guest.Cursor = Cursors.Hand;
        guest.UseMnemonic = false;
        Controls.Add(guest);
        demo = new Label();
        demo.Name = "demo";
        demo.Location = new Point(32, 454);
        demo.Size = new Size(500, 70);
        demo.TabIndex = 9;
        demo.Text = "Demo accounts: admin / staff / customer @custompc.local\nPassword for all demo accounts: CustomPC123!";
        demo.UseMnemonic = false;
        Controls.Add(demo);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(580, 580);
        MinimumSize = new Size(596, 619);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Welcome to CustomPC";
        Name = "LoginForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label emailLabel = null!;
    private TextBox email = null!;
    private Label passwordLabel = null!;
    private TextBox password = null!;
    private Button login = null!;
    private Button register = null!;
    private Button guest = null!;
    private Label demo = null!;
}
