#nullable enable
namespace CustomPC;

partial class OrdersForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(1036, 40);
        heading.TabIndex = 0;
        heading.Text = "Orders & payments";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(1036, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Present the receipt at the store. Staff confirm payments and update order progress.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        searchLabel = new Label();
        searchLabel.Name = "searchLabel";
        searchLabel.Location = new Point(32, 120);
        searchLabel.Size = new Size(440, 28);
        searchLabel.TabIndex = 2;
        searchLabel.Text = "Order number or customer";
        searchLabel.UseMnemonic = false;
        Controls.Add(searchLabel);
        search = new TextBox();
        search.Name = "search";
        search.Location = new Point(32, 150);
        search.Size = new Size(440, 32);
        search.TabIndex = 3;
        Controls.Add(search);
        statusLabel = new Label();
        statusLabel.Name = "statusLabel";
        statusLabel.Location = new Point(496, 120);
        statusLabel.Size = new Size(260, 28);
        statusLabel.TabIndex = 4;
        statusLabel.Text = "Order status";
        statusLabel.UseMnemonic = false;
        Controls.Add(statusLabel);
        status = new ComboBox();
        status.Name = "status";
        status.Location = new Point(496, 150);
        status.Size = new Size(260, 32);
        status.TabIndex = 5;
        status.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(status);
        grid = new DataGridView();
        grid.Name = "grid";
        grid.Location = new Point(32, 202);
        grid.Size = new Size(1036, 408);
        grid.TabIndex = 6;
        grid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        grid.BackgroundColor = Color.White;
        grid.BorderStyle = BorderStyle.None;
        grid.ReadOnly = true;
        grid.AllowUserToAddRows = false;
        grid.AllowUserToDeleteRows = false;
        grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        grid.MultiSelect = false;
        grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        grid.RowHeadersVisible = false;
        grid.EnableHeadersVisualStyles = false;
        grid.ColumnHeadersHeight = 42;
        grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
        grid.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
        grid.RowTemplate.Height = 38;
        grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(204, 235, 225);
        grid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        Controls.Add(grid);
        receipt = new Button();
        receipt.Name = "receipt";
        receipt.Location = new Point(32, 636);
        receipt.Size = new Size(204, 40);
        receipt.TabIndex = 7;
        receipt.Text = "View / print receipt";
        receipt.BackColor = Color.FromArgb(15, 98, 84);
        receipt.ForeColor = Color.White;
        receipt.FlatStyle = FlatStyle.Flat;
        receipt.FlatAppearance.BorderSize = 0;
        receipt.Cursor = Cursors.Hand;
        receipt.UseMnemonic = false;
        Controls.Add(receipt);
        pay = new Button();
        pay.Name = "pay";
        pay.Location = new Point(252, 636);
        pay.Size = new Size(220, 40);
        pay.TabIndex = 8;
        pay.Text = "Confirm store payment";
        pay.BackColor = Color.FromArgb(15, 98, 84);
        pay.ForeColor = Color.White;
        pay.FlatStyle = FlatStyle.Flat;
        pay.FlatAppearance.BorderSize = 0;
        pay.Cursor = Cursors.Hand;
        pay.UseMnemonic = false;
        Controls.Add(pay);
        advance = new Button();
        advance.Name = "advance";
        advance.Location = new Point(488, 636);
        advance.Size = new Size(180, 40);
        advance.TabIndex = 9;
        advance.Text = "Next order stage";
        advance.BackColor = Color.FromArgb(15, 98, 84);
        advance.ForeColor = Color.White;
        advance.FlatStyle = FlatStyle.Flat;
        advance.FlatAppearance.BorderSize = 0;
        advance.Cursor = Cursors.Hand;
        advance.UseMnemonic = false;
        Controls.Add(advance);
        cancel = new Button();
        cancel.Name = "cancel";
        cancel.Location = new Point(684, 636);
        cancel.Size = new Size(204, 40);
        cancel.TabIndex = 10;
        cancel.Text = "Cancel unpaid order";
        cancel.BackColor = Color.FromArgb(15, 98, 84);
        cancel.ForeColor = Color.White;
        cancel.FlatStyle = FlatStyle.Flat;
        cancel.FlatAppearance.BorderSize = 0;
        cancel.Cursor = Cursors.Hand;
        cancel.UseMnemonic = false;
        Controls.Add(cancel);
        refresh = new Button();
        refresh.Name = "refresh";
        refresh.Location = new Point(904, 636);
        refresh.Size = new Size(164, 40);
        refresh.TabIndex = 11;
        refresh.Text = "Refresh";
        refresh.BackColor = Color.FromArgb(15, 98, 84);
        refresh.ForeColor = Color.White;
        refresh.FlatStyle = FlatStyle.Flat;
        refresh.FlatAppearance.BorderSize = 0;
        refresh.Cursor = Cursors.Hand;
        refresh.UseMnemonic = false;
        Controls.Add(refresh);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1100, 720);
        MinimumSize = new Size(1116, 759);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Orders & payments";
        Name = "OrdersForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label searchLabel = null!;
    private TextBox search = null!;
    private Label statusLabel = null!;
    private ComboBox status = null!;
    private DataGridView grid = null!;
    private Button receipt = null!;
    private Button pay = null!;
    private Button advance = null!;
    private Button cancel = null!;
    private Button refresh = null!;
}
