#nullable enable
namespace CustomPC;

partial class PartEditForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(496, 40);
        heading.TabIndex = 0;
        heading.Text = "Component details";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(496, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Store specifications used by the compatibility checker.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        partNameLabel = new Label();
        partNameLabel.Name = "partNameLabel";
        partNameLabel.Location = new Point(32, 128);
        partNameLabel.Size = new Size(480, 28);
        partNameLabel.TabIndex = 2;
        partNameLabel.Text = "Component name";
        partNameLabel.UseMnemonic = false;
        Controls.Add(partNameLabel);
        partName = new TextBox();
        partName.Name = "partName";
        partName.Location = new Point(32, 158);
        partName.Size = new Size(480, 32);
        partName.TabIndex = 3;
        Controls.Add(partName);
        categoryLabel = new Label();
        categoryLabel.Name = "categoryLabel";
        categoryLabel.Location = new Point(32, 208);
        categoryLabel.Size = new Size(220, 28);
        categoryLabel.TabIndex = 4;
        categoryLabel.Text = "Category";
        categoryLabel.UseMnemonic = false;
        Controls.Add(categoryLabel);
        category = new ComboBox();
        category.Name = "category";
        category.Location = new Point(32, 238);
        category.Size = new Size(220, 32);
        category.TabIndex = 5;
        category.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(category);
        brandLabel = new Label();
        brandLabel.Name = "brandLabel";
        brandLabel.Location = new Point(276, 208);
        brandLabel.Size = new Size(236, 28);
        brandLabel.TabIndex = 6;
        brandLabel.Text = "Brand";
        brandLabel.UseMnemonic = false;
        Controls.Add(brandLabel);
        brand = new TextBox();
        brand.Name = "brand";
        brand.Location = new Point(276, 238);
        brand.Size = new Size(236, 32);
        brand.TabIndex = 7;
        Controls.Add(brand);
        priceLabel = new Label();
        priceLabel.Name = "priceLabel";
        priceLabel.Location = new Point(32, 288);
        priceLabel.Size = new Size(220, 28);
        priceLabel.TabIndex = 8;
        priceLabel.Text = "Unit price (PHP)";
        priceLabel.UseMnemonic = false;
        Controls.Add(priceLabel);
        price = new NumericUpDown();
        price.Name = "price";
        price.Location = new Point(32, 318);
        price.Size = new Size(220, 32);
        price.TabIndex = 9;
        price.Maximum = 10000000;
        price.ThousandsSeparator = true;
        price.DecimalPlaces = 2;
        Controls.Add(price);
        stockLabel = new Label();
        stockLabel.Name = "stockLabel";
        stockLabel.Location = new Point(276, 288);
        stockLabel.Size = new Size(236, 28);
        stockLabel.TabIndex = 10;
        stockLabel.Text = "On-hand stock";
        stockLabel.UseMnemonic = false;
        Controls.Add(stockLabel);
        stock = new NumericUpDown();
        stock.Name = "stock";
        stock.Location = new Point(276, 318);
        stock.Size = new Size(236, 32);
        stock.TabIndex = 11;
        stock.Maximum = 10000000;
        stock.ThousandsSeparator = true;
        Controls.Add(stock);
        specificationsLabel = new Label();
        specificationsLabel.Name = "specificationsLabel";
        specificationsLabel.Location = new Point(32, 368);
        specificationsLabel.Size = new Size(480, 28);
        specificationsLabel.TabIndex = 12;
        specificationsLabel.Text = "Specifications";
        specificationsLabel.UseMnemonic = false;
        Controls.Add(specificationsLabel);
        specifications = new TextBox();
        specifications.Name = "specifications";
        specifications.Location = new Point(32, 398);
        specifications.Size = new Size(480, 32);
        specifications.TabIndex = 13;
        Controls.Add(specifications);
        socketLabel = new Label();
        socketLabel.Name = "socketLabel";
        socketLabel.Location = new Point(32, 448);
        socketLabel.Size = new Size(220, 28);
        socketLabel.TabIndex = 14;
        socketLabel.Text = "CPU / board socket";
        socketLabel.UseMnemonic = false;
        Controls.Add(socketLabel);
        socket = new TextBox();
        socket.Name = "socket";
        socket.Location = new Point(32, 478);
        socket.Size = new Size(220, 32);
        socket.TabIndex = 15;
        Controls.Add(socket);
        memoryLabel = new Label();
        memoryLabel.Name = "memoryLabel";
        memoryLabel.Location = new Point(276, 448);
        memoryLabel.Size = new Size(236, 28);
        memoryLabel.TabIndex = 16;
        memoryLabel.Text = "RAM / board memory type";
        memoryLabel.UseMnemonic = false;
        Controls.Add(memoryLabel);
        memory = new TextBox();
        memory.Name = "memory";
        memory.Location = new Point(276, 478);
        memory.Size = new Size(236, 32);
        memory.TabIndex = 17;
        Controls.Add(memory);
        wattsLabel = new Label();
        wattsLabel.Name = "wattsLabel";
        wattsLabel.Location = new Point(32, 528);
        wattsLabel.Size = new Size(220, 28);
        wattsLabel.TabIndex = 18;
        wattsLabel.Text = "Watts (PSU = capacity)";
        wattsLabel.UseMnemonic = false;
        Controls.Add(wattsLabel);
        watts = new NumericUpDown();
        watts.Name = "watts";
        watts.Location = new Point(32, 558);
        watts.Size = new Size(220, 32);
        watts.TabIndex = 19;
        watts.Maximum = 10000000;
        watts.ThousandsSeparator = true;
        Controls.Add(watts);
        lowLabel = new Label();
        lowLabel.Name = "lowLabel";
        lowLabel.Location = new Point(276, 528);
        lowLabel.Size = new Size(236, 28);
        lowLabel.TabIndex = 20;
        lowLabel.Text = "Low-stock threshold";
        lowLabel.UseMnemonic = false;
        Controls.Add(lowLabel);
        low = new NumericUpDown();
        low.Name = "low";
        low.Location = new Point(276, 558);
        low.Size = new Size(236, 32);
        low.TabIndex = 21;
        low.Maximum = 10000000;
        low.ThousandsSeparator = true;
        Controls.Add(low);
        supplierLabel = new Label();
        supplierLabel.Name = "supplierLabel";
        supplierLabel.Location = new Point(32, 608);
        supplierLabel.Size = new Size(480, 28);
        supplierLabel.TabIndex = 22;
        supplierLabel.Text = "Supplier";
        supplierLabel.UseMnemonic = false;
        Controls.Add(supplierLabel);
        supplier = new ComboBox();
        supplier.Name = "supplier";
        supplier.Location = new Point(32, 638);
        supplier.Size = new Size(480, 32);
        supplier.TabIndex = 23;
        supplier.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(supplier);
        archived = new CheckBox();
        archived.Name = "archived";
        archived.Location = new Point(32, 700);
        archived.Size = new Size(240, 32);
        archived.TabIndex = 24;
        archived.Text = "Archive this part";
        Controls.Add(archived);
        save = new Button();
        save.Name = "save";
        save.Location = new Point(292, 696);
        save.Size = new Size(220, 40);
        save.TabIndex = 25;
        save.Text = "Save component";
        save.BackColor = Color.FromArgb(15, 98, 84);
        save.ForeColor = Color.White;
        save.FlatStyle = FlatStyle.Flat;
        save.FlatAppearance.BorderSize = 0;
        save.Cursor = Cursors.Hand;
        save.UseMnemonic = false;
        Controls.Add(save);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(560, 760);
        MinimumSize = new Size(576, 480);
        AutoScroll = true;
        AutoScrollMinSize = new Size(540, 760);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Component details";
        Name = "PartEditForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label partNameLabel = null!;
    private TextBox partName = null!;
    private Label categoryLabel = null!;
    private ComboBox category = null!;
    private Label brandLabel = null!;
    private TextBox brand = null!;
    private Label priceLabel = null!;
    private NumericUpDown price = null!;
    private Label stockLabel = null!;
    private NumericUpDown stock = null!;
    private Label specificationsLabel = null!;
    private TextBox specifications = null!;
    private Label socketLabel = null!;
    private TextBox socket = null!;
    private Label memoryLabel = null!;
    private TextBox memory = null!;
    private Label wattsLabel = null!;
    private NumericUpDown watts = null!;
    private Label lowLabel = null!;
    private NumericUpDown low = null!;
    private Label supplierLabel = null!;
    private ComboBox supplier = null!;
    private CheckBox archived = null!;
    private Button save = null!;
}
