#nullable enable
namespace CustomPC;

partial class RegisterForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(516, 40);
        heading.TabIndex = 0;
        heading.Text = "Create an account";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(516, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Customer accounts can build PCs and place orders.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        fullNameLabel = new Label();
        fullNameLabel.Name = "fullNameLabel";
        fullNameLabel.Location = new Point(32, 136);
        fullNameLabel.Size = new Size(480, 28);
        fullNameLabel.TabIndex = 2;
        fullNameLabel.Text = "Full name";
        fullNameLabel.UseMnemonic = false;
        Controls.Add(fullNameLabel);
        fullName = new TextBox();
        fullName.Name = "fullName";
        fullName.Location = new Point(32, 166);
        fullName.Size = new Size(480, 32);
        fullName.TabIndex = 3;
        Controls.Add(fullName);
        emailLabel = new Label();
        emailLabel.Name = "emailLabel";
        emailLabel.Location = new Point(32, 216);
        emailLabel.Size = new Size(480, 28);
        emailLabel.TabIndex = 4;
        emailLabel.Text = "Email address";
        emailLabel.UseMnemonic = false;
        Controls.Add(emailLabel);
        email = new TextBox();
        email.Name = "email";
        email.Location = new Point(32, 246);
        email.Size = new Size(480, 32);
        email.TabIndex = 5;
        Controls.Add(email);
        passwordLabel = new Label();
        passwordLabel.Name = "passwordLabel";
        passwordLabel.Location = new Point(32, 296);
        passwordLabel.Size = new Size(480, 28);
        passwordLabel.TabIndex = 6;
        passwordLabel.Text = "Password (at least 8 characters)";
        passwordLabel.UseMnemonic = false;
        Controls.Add(passwordLabel);
        password = new TextBox();
        password.Name = "password";
        password.Location = new Point(32, 326);
        password.Size = new Size(480, 32);
        password.TabIndex = 7;
        password.UseSystemPasswordChar = true;
        Controls.Add(password);
        confirmLabel = new Label();
        confirmLabel.Name = "confirmLabel";
        confirmLabel.Location = new Point(32, 376);
        confirmLabel.Size = new Size(480, 28);
        confirmLabel.TabIndex = 8;
        confirmLabel.Text = "Confirm password";
        confirmLabel.UseMnemonic = false;
        Controls.Add(confirmLabel);
        confirm = new TextBox();
        confirm.Name = "confirm";
        confirm.Location = new Point(32, 406);
        confirm.Size = new Size(480, 32);
        confirm.TabIndex = 9;
        confirm.UseSystemPasswordChar = true;
        Controls.Add(confirm);
        save = new Button();
        save.Name = "save";
        save.Location = new Point(32, 480);
        save.Size = new Size(480, 40);
        save.TabIndex = 10;
        save.Text = "Create account";
        save.BackColor = Color.FromArgb(15, 98, 84);
        save.ForeColor = Color.White;
        save.FlatStyle = FlatStyle.Flat;
        save.FlatAppearance.BorderSize = 0;
        save.Cursor = Cursors.Hand;
        save.UseMnemonic = false;
        Controls.Add(save);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(580, 560);
        MinimumSize = new Size(596, 599);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Create an account";
        Name = "RegisterForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label fullNameLabel = null!;
    private TextBox fullName = null!;
    private Label emailLabel = null!;
    private TextBox email = null!;
    private Label passwordLabel = null!;
    private TextBox password = null!;
    private Label confirmLabel = null!;
    private TextBox confirm = null!;
    private Button save = null!;
}
