#nullable enable
namespace CustomPC;

partial class ReportsForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(1036, 40);
        heading.TabIndex = 0;
        heading.Text = "Business reports";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(1036, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Filter operational records by date and export the current view as CSV.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        reportLabel = new Label();
        reportLabel.Name = "reportLabel";
        reportLabel.Location = new Point(32, 120);
        reportLabel.Size = new Size(260, 28);
        reportLabel.TabIndex = 2;
        reportLabel.Text = "Report";
        reportLabel.UseMnemonic = false;
        Controls.Add(reportLabel);
        report = new ComboBox();
        report.Name = "report";
        report.Location = new Point(32, 150);
        report.Size = new Size(260, 32);
        report.TabIndex = 3;
        report.DropDownStyle = ComboBoxStyle.DropDownList;
        Controls.Add(report);
        fromLabel = new Label();
        fromLabel.Name = "fromLabel";
        fromLabel.Location = new Point(316, 120);
        fromLabel.Size = new Size(220, 28);
        fromLabel.TabIndex = 4;
        fromLabel.Text = "From";
        fromLabel.UseMnemonic = false;
        Controls.Add(fromLabel);
        from = new DateTimePicker();
        from.Name = "from";
        from.Location = new Point(316, 150);
        from.Size = new Size(220, 32);
        from.TabIndex = 5;
        from.Format = DateTimePickerFormat.Short;
        Controls.Add(from);
        toLabel = new Label();
        toLabel.Name = "toLabel";
        toLabel.Location = new Point(560, 120);
        toLabel.Size = new Size(220, 28);
        toLabel.TabIndex = 6;
        toLabel.Text = "Through";
        toLabel.UseMnemonic = false;
        Controls.Add(toLabel);
        to = new DateTimePicker();
        to.Name = "to";
        to.Location = new Point(560, 150);
        to.Size = new Size(220, 32);
        to.TabIndex = 7;
        to.Format = DateTimePickerFormat.Short;
        Controls.Add(to);
        refresh = new Button();
        refresh.Name = "refresh";
        refresh.Location = new Point(804, 146);
        refresh.Size = new Size(264, 40);
        refresh.TabIndex = 8;
        refresh.Text = "Generate report";
        refresh.BackColor = Color.FromArgb(15, 98, 84);
        refresh.ForeColor = Color.White;
        refresh.FlatStyle = FlatStyle.Flat;
        refresh.FlatAppearance.BorderSize = 0;
        refresh.Cursor = Cursors.Hand;
        refresh.UseMnemonic = false;
        Controls.Add(refresh);
        summary = new Label();
        summary.Name = "summary";
        summary.Location = new Point(32, 200);
        summary.Size = new Size(1036, 42);
        summary.TabIndex = 9;
        summary.Text = "Report summary";
        summary.UseMnemonic = false;
        summary.Font = new Font("Segoe UI", 13F, FontStyle.Bold);
        Controls.Add(summary);
        grid = new DataGridView();
        grid.Name = "grid";
        grid.Location = new Point(32, 252);
        grid.Size = new Size(1036, 364);
        grid.TabIndex = 10;
        grid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        grid.BackgroundColor = Color.White;
        grid.BorderStyle = BorderStyle.None;
        grid.ReadOnly = true;
        grid.AllowUserToAddRows = false;
        grid.AllowUserToDeleteRows = false;
        grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        grid.MultiSelect = false;
        grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        grid.RowHeadersVisible = false;
        grid.EnableHeadersVisualStyles = false;
        grid.ColumnHeadersHeight = 42;
        grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(30, 41, 59);
        grid.ColumnHeadersDefaultCellStyle.ForeColor = Color.White;
        grid.RowTemplate.Height = 38;
        grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(204, 235, 225);
        grid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        Controls.Add(grid);
        export = new Button();
        export.Name = "export";
        export.Location = new Point(32, 644);
        export.Size = new Size(220, 40);
        export.TabIndex = 11;
        export.Text = "Export CSV";
        export.BackColor = Color.FromArgb(15, 98, 84);
        export.ForeColor = Color.White;
        export.FlatStyle = FlatStyle.Flat;
        export.FlatAppearance.BorderSize = 0;
        export.Cursor = Cursors.Hand;
        export.UseMnemonic = false;
        Controls.Add(export);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1100, 720);
        MinimumSize = new Size(1116, 759);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Business reports";
        Name = "ReportsForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label reportLabel = null!;
    private ComboBox report = null!;
    private Label fromLabel = null!;
    private DateTimePicker from = null!;
    private Label toLabel = null!;
    private DateTimePicker to = null!;
    private Button refresh = null!;
    private Label summary = null!;
    private DataGridView grid = null!;
    private Button export = null!;
}
