#nullable enable
namespace CustomPC;

partial class SupplierEditForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        SuspendLayout();
        heading = new Label();
        heading.Name = "heading";
        heading.Location = new Point(32, 24);
        heading.Size = new Size(516, 40);
        heading.TabIndex = 0;
        heading.Text = "Supplier details";
        heading.UseMnemonic = false;
        heading.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        Controls.Add(heading);
        subheading = new Label();
        subheading.Name = "subheading";
        subheading.Location = new Point(32, 72);
        subheading.Size = new Size(516, 40);
        subheading.TabIndex = 1;
        subheading.Text = "Record the supplier and link their components in Parts & inventory.";
        subheading.UseMnemonic = false;
        subheading.ForeColor = Color.FromArgb(71, 85, 105);
        Controls.Add(subheading);
        supplierNameLabel = new Label();
        supplierNameLabel.Name = "supplierNameLabel";
        supplierNameLabel.Location = new Point(32, 136);
        supplierNameLabel.Size = new Size(480, 28);
        supplierNameLabel.TabIndex = 2;
        supplierNameLabel.Text = "Supplier name";
        supplierNameLabel.UseMnemonic = false;
        Controls.Add(supplierNameLabel);
        supplierName = new TextBox();
        supplierName.Name = "supplierName";
        supplierName.Location = new Point(32, 166);
        supplierName.Size = new Size(480, 32);
        supplierName.TabIndex = 3;
        Controls.Add(supplierName);
        contactLabel = new Label();
        contactLabel.Name = "contactLabel";
        contactLabel.Location = new Point(32, 216);
        contactLabel.Size = new Size(480, 28);
        contactLabel.TabIndex = 4;
        contactLabel.Text = "Contact person / phone";
        contactLabel.UseMnemonic = false;
        Controls.Add(contactLabel);
        contact = new TextBox();
        contact.Name = "contact";
        contact.Location = new Point(32, 246);
        contact.Size = new Size(480, 32);
        contact.TabIndex = 5;
        Controls.Add(contact);
        emailLabel = new Label();
        emailLabel.Name = "emailLabel";
        emailLabel.Location = new Point(32, 296);
        emailLabel.Size = new Size(480, 28);
        emailLabel.TabIndex = 6;
        emailLabel.Text = "Email";
        emailLabel.UseMnemonic = false;
        Controls.Add(emailLabel);
        email = new TextBox();
        email.Name = "email";
        email.Location = new Point(32, 326);
        email.Size = new Size(480, 32);
        email.TabIndex = 7;
        Controls.Add(email);
        addressLabel = new Label();
        addressLabel.Name = "addressLabel";
        addressLabel.Location = new Point(32, 376);
        addressLabel.Size = new Size(480, 28);
        addressLabel.TabIndex = 8;
        addressLabel.Text = "Address";
        addressLabel.UseMnemonic = false;
        Controls.Add(addressLabel);
        address = new TextBox();
        address.Name = "address";
        address.Location = new Point(32, 406);
        address.Size = new Size(480, 32);
        address.TabIndex = 9;
        Controls.Add(address);
        archived = new CheckBox();
        archived.Name = "archived";
        archived.Location = new Point(32, 466);
        archived.Size = new Size(300, 32);
        archived.TabIndex = 10;
        archived.Text = "Archive supplier";
        Controls.Add(archived);
        save = new Button();
        save.Name = "save";
        save.Location = new Point(32, 522);
        save.Size = new Size(480, 40);
        save.TabIndex = 11;
        save.Text = "Save supplier";
        save.BackColor = Color.FromArgb(15, 98, 84);
        save.ForeColor = Color.White;
        save.FlatStyle = FlatStyle.Flat;
        save.FlatAppearance.BorderSize = 0;
        save.Cursor = Cursors.Hand;
        save.UseMnemonic = false;
        Controls.Add(save);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        Font = new Font("Segoe UI", 10F);
        ForeColor = Color.FromArgb(15, 23, 42);
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(580, 610);
        MinimumSize = new Size(596, 649);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "CustomPC | Supplier details";
        Name = "SupplierEditForm";
        ResumeLayout(false);
        PerformLayout();
    }
    private Label heading = null!;
    private Label subheading = null!;
    private Label supplierNameLabel = null!;
    private TextBox supplierName = null!;
    private Label contactLabel = null!;
    private TextBox contact = null!;
    private Label emailLabel = null!;
    private TextBox email = null!;
    private Label addressLabel = null!;
    private TextBox address = null!;
    private CheckBox archived = null!;
    private Button save = null!;
}
